%% -------------------------------------------------------------------------------
%% THIS FILE IS ORIGINALLY GENERATED BY THE DESIGNER.
%% YOU ARE ONLY ALLOWED TO MODIFY CODE BETWEEN '%%<<< BEGIN' AND '%%<<< END'.
%% PLEASE MODIFY AND REGENERETE IT IN THE DESIGNER FOR CLASS/MEMBERS/METHODS, ETC.
%% -------------------------------------------------------------------------------

-module('my_agent').

-compile([nowarn_unused_vars]).

-include("ebt.hrl").

-export([agent/0]).
-export([get_var/2, set_var/3]).
-export([return_behaviac_status/2]).
-export([return_behaviac_status_with_int/2]).
-export([return_behaviac_status_with_int_bool/2]).
-export([return_ebt_status/2]).
-export([return_ebt_status_with_int/2]).
-export([return_ebt_status_with_int_bool/2]).
-export([return_int/2]).
-export([return_int_with_int/2]).
-export([return_int_with_int_bool/2]).
-export([return_void/2]).
-export([return_void_with_int/2]).
-export([return_void_with_int_bool/2]).

%%<<< BEGIN WRITING YOUR CODE FILE_INIT
-include_lib("eunit/include/eunit.hrl").
%%<<< END WRITING YOUR CODE

-record('my_agent', {
object,
	'IntArray' = [1,2,3],
	'Int' = 123,
	'EBTStatus' = ?SUCCESS,
	'Bool' = false,
	'BehaviacEBTStatus' = ?SUCCESS
}).

agent() ->
	#'my_agent'{}.

get_var(Agent, 'IntArray') ->
	Agent#'my_agent'.'IntArray';
get_var(Agent, 'Int') ->
	Agent#'my_agent'.'Int';
get_var(Agent, 'EBTStatus') ->
	Agent#'my_agent'.'EBTStatus';
get_var(Agent, 'Bool') ->
	Agent#'my_agent'.'Bool';
get_var(Agent, 'BehaviacEBTStatus') ->
	Agent#'my_agent'.'BehaviacEBTStatus';
get_var(Agent, Key) ->
	throw({unknown_field, Agent, Key}).

set_var(Agent, 'IntArray', Val) ->
	Agent#'my_agent'{'IntArray' = Val};
set_var(Agent, 'Int', Val) ->
	Agent#'my_agent'{'Int' = Val};
set_var(Agent, 'EBTStatus', Val) ->
	Agent#'my_agent'{'EBTStatus' = Val};
set_var(Agent, 'Bool', Val) ->
	Agent#'my_agent'{'Bool' = Val};
set_var(Agent, 'BehaviacEBTStatus', Val) ->
	Agent#'my_agent'{'BehaviacEBTStatus' = Val};
set_var(Agent, Key, _Val) ->
	throw({unknown_field, Agent, Key}).

%% return_behaviac_status
return_behaviac_status(Agent, []) ->
%%<<< BEGIN WRITING YOUR CODE return_behaviac_status
	?SUCCESS.
%%<<< END WRITING YOUR CODE

%% return_behaviac_status_with_int
return_behaviac_status_with_int(Agent, [ParamInt]) ->
%%<<< BEGIN WRITING YOUR CODE return_behaviac_status_with_int
	?debugFmt("Param:~w", [ParamInt]),
	?SUCCESS.
%%<<< END WRITING YOUR CODE

%% return_behaviac_status_with_int_bool
return_behaviac_status_with_int_bool(Agent, [ParamInt, ParamBool]) ->
%%<<< BEGIN WRITING YOUR CODE return_behaviac_status_with_int_bool
	?debugFmt("Param:~w", [{ParamInt, ParamBool}]),
	?SUCCESS.
%%<<< END WRITING YOUR CODE

%% return_ebt_status
return_ebt_status(Agent, []) ->
%%<<< BEGIN WRITING YOUR CODE return_ebt_status
	?SUCCESS.
%%<<< END WRITING YOUR CODE

%% return_ebt_status_with_int
return_ebt_status_with_int(Agent, [ParamInt]) ->
%%<<< BEGIN WRITING YOUR CODE return_ebt_status_with_int
	?debugFmt("Param:~w", [ParamInt]),
	?SUCCESS.
%%<<< END WRITING YOUR CODE

%% return_ebt_status_with_int_bool
return_ebt_status_with_int_bool(Agent, [ParamInt, ParamBool]) ->
%%<<< BEGIN WRITING YOUR CODE return_ebt_status_with_int_bool
	?debugFmt("Param:~w", [{ParamInt, ParamBool}]),
	?SUCCESS.
%%<<< END WRITING YOUR CODE

%% return_int
return_int(Agent, []) ->
%%<<< BEGIN WRITING YOUR CODE return_int
	123.
%%<<< END WRITING YOUR CODE

%% return_int_with_int
return_int_with_int(Agent, [ParamInt]) ->
%%<<< BEGIN WRITING YOUR CODE return_int_with_int
	ParamInt.
%%<<< END WRITING YOUR CODE

%% return_int_with_int_bool
return_int_with_int_bool(Agent, [ParamInt, ParamBool]) ->
%%<<< BEGIN WRITING YOUR CODE return_int_with_int_bool
	{ParamInt, ParamBool}.
%%<<< END WRITING YOUR CODE

%% return_void
return_void(Agent, []) ->
%%<<< BEGIN WRITING YOUR CODE return_void
	?debugHere,
	ok.
%%<<< END WRITING YOUR CODE

%% return_void_with_int
return_void_with_int(Agent, [ParamInt]) ->
%%<<< BEGIN WRITING YOUR CODE return_void_with_int
	ok.
%%<<< END WRITING YOUR CODE

%% return_void_with_int_bool
return_void_with_int_bool(Agent, [ParamInt, ParamBool]) ->
%%<<< BEGIN WRITING YOUR CODE return_void_with_int_bool
	ok.
%%<<< END WRITING YOUR CODE

