%% ---------------------------------------------------------------------
%% THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
%% Export file: exported/behaviac_generated/behaviors/generated_behaviors.erl
%% ---------------------------------------------------------------------

-module(generated_behaviors).

-include_lib("ebt.hrl").

-export([find/1]).

%% Source file: test_action_1
find('test_action_1') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_action,
		property = [{action,{func,'my_agent','return_behaviac_status',[]}},{result,'invalid'}],
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_action_1',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			invalid => undefined
		}
	};
%% Source file: test_action_2
find('test_action_2') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_action,
		property = [{action,{func,'my_agent','return_void',[]}},{result,'failure'}],
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_action_2',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			invalid => undefined
		}
	};
%% Source file: test_action_3
find('test_action_3') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_action,
		property = [{action,{func,'my_agent','return_void',[]}},{result,{func,'my_agent','return_behaviac_status',[]}}],
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_action_3',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			invalid => undefined
		}
	};
%% Source file: test_action_4
find('test_action_4') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_action,
		property = [{action,{func,'my_agent','return_void',[]}},{result,{func,'my_agent','return_behaviac_status',[]}}],
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_action_4',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			invalid => undefined
		}
	};
%% Source file: test_action_5
find('test_action_5') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_action,
		property = [{action,{func,'my_agent','return_int_with_int',[{var,'Int'}]}},{result,{func,'my_agent','return_behaviac_status_with_int',[0]}}],
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_action_5',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			invalid => undefined
		}
	};
%% Source file: test_and_1
find('test_and_1') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_and,
		children = [1,2],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node1 = #ebt_node{
		id = 1,
		executor = ebt_true,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node2 = #ebt_node{
		id = 2,
		executor = ebt_true,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_and_1',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			1 => Node1,
			2 => Node2,
			invalid => undefined
		}
	};
%% Source file: test_and_2
find('test_and_2') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_and,
		children = [1,2],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node1 = #ebt_node{
		id = 1,
		executor = ebt_true,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node2 = #ebt_node{
		id = 2,
		executor = ebt_false,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_and_2',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			1 => Node1,
			2 => Node2,
			invalid => undefined
		}
	};
%% Source file: test_and_3
find('test_and_3') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_and,
		children = [1,2],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node1 = #ebt_node{
		id = 1,
		executor = ebt_false,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node2 = #ebt_node{
		id = 2,
		executor = ebt_true,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_and_3',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			1 => Node1,
			2 => Node2,
			invalid => undefined
		}
	};
%% Source file: test_and_4
find('test_and_4') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_and,
		children = [1,2],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node1 = #ebt_node{
		id = 1,
		executor = ebt_false,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node2 = #ebt_node{
		id = 2,
		executor = ebt_false,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_and_4',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			1 => Node1,
			2 => Node2,
			invalid => undefined
		}
	};
%% Source file: test_assign_1
find('test_assign_1') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_assign,
		property = [{assign,{{var,'Int'},100}}],
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_assign_1',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			invalid => undefined
		}
	};
%% Source file: test_assign_2
find('test_assign_2') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_assign,
		property = [{assign,{{var,'IntArray',0},100}}],
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_assign_2',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			invalid => undefined
		}
	};
%% Source file: test_compute_1
find('test_compute_1') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_compute,
		property = [{compute,{'+',{var,'Int'},1,2}}],
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_compute_1',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			invalid => undefined
		}
	};
%% Source file: test_compute_2
find('test_compute_2') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_compute,
		property = [{compute,{'+',{var,'Int'},{var,'Int'},1}}],
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_compute_2',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			invalid => undefined
		}
	};
%% Source file: test_condition_1
find('test_condition_1') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_condition,
		property = [{compare,{'==',{var,'Int'},10}}],
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_condition_1',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			invalid => undefined
		}
	};
%% Source file: test_condition_2
find('test_condition_2') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_condition,
		property = [{compare,{'==',{var,'Int'},123}}],
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_condition_2',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			invalid => undefined
		}
	};
%% Source file: test_condition_3
find('test_condition_3') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_condition,
		property = [{compare,{'==',{func,'my_agent','return_int',[]},10}}],
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_condition_3',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			invalid => undefined
		}
	};
%% Source file: test_condition_4
find('test_condition_4') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_condition,
		property = [{compare,{'==',{func,'my_agent','return_int',[]},123}}],
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_condition_4',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			invalid => undefined
		}
	};
%% Source file: test_condition_5
find('test_condition_5') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_condition,
		property = [{compare,{'==',{func,'my_agent','return_int',[]},{var,'Int'}}}],
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_condition_5',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			invalid => undefined
		}
	};
%% Source file: test_condition_6
find('test_condition_6') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_condition,
		property = [{compare,{'==',{func,'my_agent','return_int',[]},{func,'my_agent','return_int',[]}}}],
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_condition_6',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			invalid => undefined
		}
	};
%% Source file: test_condition_7
find('test_condition_7') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_condition,
		property = [{compare,{'==',{func,'my_agent','return_int',[]},{func,'my_agent','return_int_with_int',[10]}}}],
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_condition_7',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			invalid => undefined
		}
	};
%% Source file: test_condition_8
find('test_condition_8') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_condition,
		property = [{compare,{'==',{func,'my_agent','return_int',[]},{func,'my_agent','return_int_with_int',[123]}}}],
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_condition_8',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			invalid => undefined
		}
	};
%% Source file: test_count
find('test_count') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_count,
		property = [{count,3}],
		children = [1],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node1 = #ebt_node{
		id = 1,
		executor = ebt_noop,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_count',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			1 => Node1,
			invalid => undefined
		}
	};
%% Source file: test_end_1
find('test_end_1') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_end,
		property = [{result,?SUCCESS},{quit,false}],
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_end_1',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			invalid => undefined
		}
	};
%% Source file: test_end_2
find('test_end_2') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_end,
		property = [{result,?FAILURE},{quit,false}],
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_end_2',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			invalid => undefined
		}
	};
%% Source file: test_failure_1
find('test_failure_1') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_failure,
		children = [1],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node1 = #ebt_node{
		id = 1,
		executor = ebt_true,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_failure_1',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			1 => Node1,
			invalid => undefined
		}
	};
%% Source file: test_failure_2
find('test_failure_2') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_failure,
		children = [1],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node1 = #ebt_node{
		id = 1,
		executor = ebt_false,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_failure_2',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			1 => Node1,
			invalid => undefined
		}
	};
%% Source file: test_false
find('test_false') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_false,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_false',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			invalid => undefined
		}
	};
%% Source file: test_frames
find('test_frames') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_frames,
		property = [{frames,3}],
		children = [1],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node1 = #ebt_node{
		id = 1,
		executor = ebt_noop,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_frames',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			1 => Node1,
			invalid => undefined
		}
	};
%% Source file: test_if_1
find('test_if_1') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_if,
		children = [1,2,3],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node1 = #ebt_node{
		id = 1,
		executor = ebt_true,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node2 = #ebt_node{
		id = 2,
		executor = ebt_noop,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node3 = #ebt_node{
		id = 3,
		executor = ebt_noop,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_if_1',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			1 => Node1,
			2 => Node2,
			3 => Node3,
			invalid => undefined
		}
	};
%% Source file: test_if_2
find('test_if_2') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_if,
		children = [1,2,3],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node1 = #ebt_node{
		id = 1,
		executor = ebt_false,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node2 = #ebt_node{
		id = 2,
		executor = ebt_noop,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node3 = #ebt_node{
		id = 3,
		executor = ebt_noop,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_if_2',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			1 => Node1,
			2 => Node2,
			3 => Node3,
			invalid => undefined
		}
	};
%% Source file: test_loop
find('test_loop') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_loop,
		property = [{count,3},{within_frame,false}],
		children = [1],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node1 = #ebt_node{
		id = 1,
		executor = ebt_noop,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_loop',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			1 => Node1,
			invalid => undefined
		}
	};
%% Source file: test_noop
find('test_noop') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_noop,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_noop',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			invalid => undefined
		}
	};
%% Source file: test_not_1
find('test_not_1') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_not,
		children = [1],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node1 = #ebt_node{
		id = 1,
		executor = ebt_true,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_not_1',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			1 => Node1,
			invalid => undefined
		}
	};
%% Source file: test_not_2
find('test_not_2') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_not,
		children = [1],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node1 = #ebt_node{
		id = 1,
		executor = ebt_false,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_not_2',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			1 => Node1,
			invalid => undefined
		}
	};
%% Source file: test_or_1
find('test_or_1') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_or,
		children = [1,2],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node1 = #ebt_node{
		id = 1,
		executor = ebt_true,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node2 = #ebt_node{
		id = 2,
		executor = ebt_true,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_or_1',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			1 => Node1,
			2 => Node2,
			invalid => undefined
		}
	};
%% Source file: test_or_2
find('test_or_2') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_or,
		children = [1,2],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node1 = #ebt_node{
		id = 1,
		executor = ebt_true,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node2 = #ebt_node{
		id = 2,
		executor = ebt_false,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_or_2',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			1 => Node1,
			2 => Node2,
			invalid => undefined
		}
	};
%% Source file: test_or_3
find('test_or_3') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_or,
		children = [1,2],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node1 = #ebt_node{
		id = 1,
		executor = ebt_false,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node2 = #ebt_node{
		id = 2,
		executor = ebt_true,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_or_3',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			1 => Node1,
			2 => Node2,
			invalid => undefined
		}
	};
%% Source file: test_or_4
find('test_or_4') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_or,
		children = [1,2],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node1 = #ebt_node{
		id = 1,
		executor = ebt_false,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node2 = #ebt_node{
		id = 2,
		executor = ebt_false,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_or_4',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			1 => Node1,
			2 => Node2,
			invalid => undefined
		}
	};
%% Source file: test_random
find('test_random') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_random,
		children = [1,3],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node1 = #ebt_node{
		id = 1,
		executor = ebt_weight,
		property = [{weight,1}],
		children = [2],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node2 = #ebt_node{
		id = 2,
		executor = ebt_action,
		property = [{action,{func,'my_agent','return_void',[]}},{result,'success'}],
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node3 = #ebt_node{
		id = 3,
		executor = ebt_weight,
		property = [{weight,1}],
		children = [4],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node4 = #ebt_node{
		id = 4,
		executor = ebt_action,
		property = [{action,{func,'my_agent','return_void',[]}},{result,'success'}],
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_random',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			1 => Node1,
			2 => Node2,
			3 => Node3,
			4 => Node4,
			invalid => undefined
		}
	};
%% Source file: test_running_1
find('test_running_1') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_running,
		children = [1],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node1 = #ebt_node{
		id = 1,
		executor = ebt_true,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_running_1',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			1 => Node1,
			invalid => undefined
		}
	};
%% Source file: test_running_2
find('test_running_2') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_running,
		children = [1],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node1 = #ebt_node{
		id = 1,
		executor = ebt_false,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_running_2',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			1 => Node1,
			invalid => undefined
		}
	};
%% Source file: test_selector_1
find('test_selector_1') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_selector,
		children = [1,2],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node1 = #ebt_node{
		id = 1,
		executor = ebt_true,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node2 = #ebt_node{
		id = 2,
		executor = ebt_false,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_selector_1',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			1 => Node1,
			2 => Node2,
			invalid => undefined
		}
	};
%% Source file: test_selector_2
find('test_selector_2') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_selector,
		children = [1,2],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node1 = #ebt_node{
		id = 1,
		executor = ebt_false,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node2 = #ebt_node{
		id = 2,
		executor = ebt_true,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_selector_2',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			1 => Node1,
			2 => Node2,
			invalid => undefined
		}
	};
%% Source file: test_selector_3
find('test_selector_3') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_selector,
		children = [1,2],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node1 = #ebt_node{
		id = 1,
		executor = ebt_false,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node2 = #ebt_node{
		id = 2,
		executor = ebt_false,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_selector_3',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			1 => Node1,
			2 => Node2,
			invalid => undefined
		}
	};
%% Source file: test_selector_4
find('test_selector_4') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_selector,
		children = [1,2],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node1 = #ebt_node{
		id = 1,
		executor = ebt_true,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node2 = #ebt_node{
		id = 2,
		executor = ebt_true,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_selector_4',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			1 => Node1,
			2 => Node2,
			invalid => undefined
		}
	};
%% Source file: test_selector_stochastic
find('test_selector_stochastic') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_selector_stochastic,
		children = [1,2],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node1 = #ebt_node{
		id = 1,
		executor = ebt_action,
		property = [{action,{func,'my_agent','return_void',[]}},{result,'success'}],
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node2 = #ebt_node{
		id = 2,
		executor = ebt_action,
		property = [{action,{func,'my_agent','return_void',[]}},{result,'success'}],
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_selector_stochastic',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			1 => Node1,
			2 => Node2,
			invalid => undefined
		}
	};
%% Source file: test_sequence_1
find('test_sequence_1') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_sequence,
		children = [1,2],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node1 = #ebt_node{
		id = 1,
		executor = ebt_true,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node2 = #ebt_node{
		id = 2,
		executor = ebt_false,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_sequence_1',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			1 => Node1,
			2 => Node2,
			invalid => undefined
		}
	};
%% Source file: test_sequence_2
find('test_sequence_2') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_sequence,
		children = [1,2],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node1 = #ebt_node{
		id = 1,
		executor = ebt_false,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node2 = #ebt_node{
		id = 2,
		executor = ebt_true,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_sequence_2',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			1 => Node1,
			2 => Node2,
			invalid => undefined
		}
	};
%% Source file: test_sequence_3
find('test_sequence_3') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_sequence,
		children = [1,2],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node1 = #ebt_node{
		id = 1,
		executor = ebt_false,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node2 = #ebt_node{
		id = 2,
		executor = ebt_false,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_sequence_3',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			1 => Node1,
			2 => Node2,
			invalid => undefined
		}
	};
%% Source file: test_sequence_4
find('test_sequence_4') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_sequence,
		children = [1,2],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node1 = #ebt_node{
		id = 1,
		executor = ebt_true,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node2 = #ebt_node{
		id = 2,
		executor = ebt_true,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_sequence_4',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			1 => Node1,
			2 => Node2,
			invalid => undefined
		}
	};
%% Source file: test_sequence_stochastic
find('test_sequence_stochastic') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_sequence_stochastic,
		children = [1,2],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node1 = #ebt_node{
		id = 1,
		executor = ebt_action,
		property = [{action,{func,'my_agent','return_void',[]}},{result,'success'}],
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node2 = #ebt_node{
		id = 2,
		executor = ebt_action,
		property = [{action,{func,'my_agent','return_void',[]}},{result,'success'}],
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_sequence_stochastic',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			1 => Node1,
			2 => Node2,
			invalid => undefined
		}
	};
%% Source file: test_success_1
find('test_success_1') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_success,
		children = [1],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node1 = #ebt_node{
		id = 1,
		executor = ebt_true,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_success_1',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			1 => Node1,
			invalid => undefined
		}
	};
%% Source file: test_success_2
find('test_success_2') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_success,
		children = [1],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node1 = #ebt_node{
		id = 1,
		executor = ebt_false,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_success_2',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			1 => Node1,
			invalid => undefined
		}
	};
%% Source file: test_switch_1
find('test_switch_1') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_switch,
		children = [1,4],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node1 = #ebt_node{
		id = 1,
		executor = ebt_switch_case,
		children = [2,3],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node2 = #ebt_node{
		id = 2,
		executor = ebt_true,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node3 = #ebt_node{
		id = 3,
		executor = ebt_noop,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node4 = #ebt_node{
		id = 4,
		executor = ebt_switch_case,
		children = [5,6],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node5 = #ebt_node{
		id = 5,
		executor = ebt_false,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node6 = #ebt_node{
		id = 6,
		executor = ebt_noop,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_switch_1',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			1 => Node1,
			2 => Node2,
			3 => Node3,
			4 => Node4,
			5 => Node5,
			6 => Node6,
			invalid => undefined
		}
	};
%% Source file: test_switch_2
find('test_switch_2') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_switch,
		children = [1,4],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node1 = #ebt_node{
		id = 1,
		executor = ebt_switch_case,
		children = [2,3],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node2 = #ebt_node{
		id = 2,
		executor = ebt_false,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node3 = #ebt_node{
		id = 3,
		executor = ebt_noop,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node4 = #ebt_node{
		id = 4,
		executor = ebt_switch_case,
		children = [5,6],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node5 = #ebt_node{
		id = 5,
		executor = ebt_true,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node6 = #ebt_node{
		id = 6,
		executor = ebt_noop,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_switch_2',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			1 => Node1,
			2 => Node2,
			3 => Node3,
			4 => Node4,
			5 => Node5,
			6 => Node6,
			invalid => undefined
		}
	};
%% Source file: test_switch_3
find('test_switch_3') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_switch,
		children = [1,4],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node1 = #ebt_node{
		id = 1,
		executor = ebt_switch_case,
		children = [2,3],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node2 = #ebt_node{
		id = 2,
		executor = ebt_true,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node3 = #ebt_node{
		id = 3,
		executor = ebt_noop,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node4 = #ebt_node{
		id = 4,
		executor = ebt_switch_case,
		children = [5,6],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node5 = #ebt_node{
		id = 5,
		executor = ebt_true,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node6 = #ebt_node{
		id = 6,
		executor = ebt_noop,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_switch_3',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			1 => Node1,
			2 => Node2,
			3 => Node3,
			4 => Node4,
			5 => Node5,
			6 => Node6,
			invalid => undefined
		}
	};
%% Source file: test_switch_4
find('test_switch_4') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_switch,
		children = [1,4],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node1 = #ebt_node{
		id = 1,
		executor = ebt_switch_case,
		children = [2,3],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node2 = #ebt_node{
		id = 2,
		executor = ebt_false,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node3 = #ebt_node{
		id = 3,
		executor = ebt_noop,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node4 = #ebt_node{
		id = 4,
		executor = ebt_switch_case,
		children = [5,6],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node5 = #ebt_node{
		id = 5,
		executor = ebt_false,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	Node6 = #ebt_node{
		id = 6,
		executor = ebt_noop,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_switch_4',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			1 => Node1,
			2 => Node2,
			3 => Node3,
			4 => Node4,
			5 => Node5,
			6 => Node6,
			invalid => undefined
		}
	};
%% Source file: test_true
find('test_true') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_true,
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_true',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			invalid => undefined
		}
	};
%% Source file: test_wait_frames_1
find('test_wait_frames_1') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_wait_frames,
		property = [{'frames',3}],
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_wait_frames_1',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			invalid => undefined
		}
	};
%% Source file: test_wait_frames_2
find('test_wait_frames_2') ->
	Node0 = #ebt_node{
		id = 0,
		executor = ebt_wait_frames,
		property = [{'frames',{var,'IntArray',2}}],
		children = [],
		events = [],
		preconditions = [],
		effectors = []
	},
	#ebt_tree{
		id = 'test_wait_frames_2',
		agent = 'my_agent':agent(),
		entry = 0,
		nodes = #{
			0 => Node0,
			invalid => undefined
		}
	};
find(_) ->
	undefined.
